GET http://localhost:3000/api?category=dtdd&page=1&price=[1,3]


###

POST http://localhost:3000/login
content-type: application/json

{
    "username": "datnh",
    "password": "dat123"
}

###
GET http://localhost:3000/api/search?q=samsung

###
GET localhost:3000/api/category=dtdd&brand[]=Samsung&brand[]=Xiaomi